[providers.age]
type = "age"
recipients = ["age1jqy4r7lltng327m9wzwtrwcd9pkjpveafmv8cjhv2tymdmcg93vqrc3y4j"]

[secrets]
GMAP_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dUlrT2FmRURNdXl1aTRnMWlZQ25KZ2c0TndsS01xdFBEdGpRcjdyWkRvCkJyOEkyRHgva1ZNYStETHQvWnNxSEl3NDdMV3BVZEdCS3dkNG1Mc1kxY0EKLT4gUy8uWExOUS1ncmVhc2UgOTxfbSBkTUtZIwpBcW1STkRsQgotLS0gR0lZNGkwTGZla20wV0lEOXk5VGR0SW5rTnF0aTE4U1VKeGlRUExoeWlWMAqH96DOrfEyseODSUirVI/2dcVTxSqSsAR9/0OlYJI4Bx9ECGDlknaMMWQkN3+/88zjMeUxptbw3IRPEXHgkymgEZStUSpfxg==" }
